config/routes.rb
Rails.application.routes.draw do
  root 'banks#index'
  resources :accounts do
    resources :transfers, only: [:new, :create]
  end
  resources :banks
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :bank

  attr_accessor :money # For testing purposes

  validates_presence_of :bank
  validates :owner, presence: true
  validates :number, presence: true, uniqueness: true
  monetize :money_cents, :allow_nil => false, :numericality => { :greater_than_or_equal_to => 0 }

  def print
    "#{self.owner}(#{self.number})"
  end
  def deposit(ammount)
    self.money = self.money + ammount
  end

  def subtract(ammount)
    if self.money > ammount
      self.money = self.money - ammount
    else
      raise('Enough charge in the account to do this operation')
    end
  end

  def transfer(destiny_account, money)
    transfer = Transfer.new(origin_account: self, destiny_account: destiny_account, money: money)
    transfer.save
  end
end

app/models/bank.rb
class Bank < ActiveRecord::Base

  has_many :accounts

  validates :name, presence: true, uniqueness: true

  def transfer_history
    transaction = []
    accounts.each do |a|
      transaction.push(Transfer.where("origin_account_id = #{a.id} or destiny_account_id = #{a.id}"))
    end
    transaction.first.to_a.uniq .sort_by &:created_at
  end

  def transfer_history_of(account)
    if self.accounts.include?(account)
      transaction = []
      transaction.push(Transfer.where("origin_account_id = #{account.id} or destiny_account_id = #{account.id}"))
      transaction.first.to_a.uniq .sort_by &:created_at
    else
      raise "This account doesn't exist in this bank"
    end

  end

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base

  belongs_to :origin_account, :class_name => 'Account'
  belongs_to :destiny_account, :class_name => 'Account'

  monetize :money_cents, allow_nil: false, numericality: { :greater_than => 0 }
  monetize :commission_cents, allow_nil: false, numericality: { greater_than_or_equal_to: 0 }
  validate :origin_and_destiny_is_present
  validate :origin_and_destiny_cannot_be_the_same
  validate :interbank_cannot_be_lower_than_1000
  validates :state, presence: true, inclusion: { in: %w(succeed failed initiated) }

  scope :successful, -> { where(state: 'succeed') }
  scope :failed, -> { where(state: 'failed') }

  before_save :apply_transfer

  private

  def intra_bank
    self.origin_account.bank.name == self.destiny_account.bank.name
  end

  def has_origin_and_destiny_account
    self.origin_account.present? && self.destiny_account.present?
  end

  def origin_and_destiny_is_present
    unless has_origin_and_destiny_account
      self.errors[:base] << 'Transaction must have origin and destiny account'
      return
    end
  end

  def interbank_cannot_be_lower_than_1000
    if has_origin_and_destiny_account
      unless intra_bank
        #Money gem deals with cents €1000 = 1000 *100 = 100000
        if money >= Money.new(100000)
          errors.add(:money, 'Intra-bank transactions must be lower than 1000')
        end
      end
    end
  end

  def origin_and_destiny_cannot_be_the_same
    if self.origin_account == self.destiny_account
      errors.add(:origin_account, 'must be different to destiny account')
      errors.add(:destiny_account, 'must be different to origin_account')
    end
  end

  # Intra-bank transfers, between accounts of the same bank. They don't have
  # commissions, they don't have limits and they always succeed.
  # Inter-bank transfers, between accounts of different banks. They have 5€
  # commissions, they have a limit of 1000€ per transfer. And they have a 30%
  # chance of failure.
  def apply_transfer
    if intra_bank
      self.origin_account.subtract(self.money)
      self.destiny_account.deposit(self.money)
      self.commission = 0
      self.state = 'succeed'
    else
      # 30% chance of failure.
      if rand(100) > 30
        self.origin_account.subtract(self.money + Money.new(500))
        self.destiny_account.deposit(self.money)
        self.commission = Money.new(500)
        self.state = 'succeed'
      else
        self.state = 'failed'
      end
    end
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  def show
    @transfer_history = @account.bank.transfer_history_of(@account)
  end

  # GET /accounts/new
  def new
    @account = Account.new(bank: Bank.find(params[:bank]))
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params[:account].permit(:owner, :number, :money, :bank_id )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]

  # GET /banks
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  def show
    @accounts = @bank.accounts
    @transfer_history = @bank.transfer_history
  end

  # GET /banks/new
  def new
    @bank = Bank.new
  end

  # GET /banks/1/edit
  def edit
  end

  # POST /banks
  def create
    @bank = Bank.new(bank_params)

    if @bank.save
      redirect_to @bank, notice: 'Bank was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /banks/1
  def update
    if @bank.update(bank_params)
      redirect_to @bank, notice: 'Bank was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /banks/1
  def destroy
    @bank.destroy
    redirect_to banks_url, notice: 'Bank was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bank_params
      params.require(:bank).permit(:name)
    end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]

  # GET /transfers/new
  def new
    @origin_account = Account.find(params[:account_id])
    @transfer = Transfer.new(origin_account: @origin_account)
    @destiny_accounts = Account.where.not(id: @origin_account.id)
  end

  # POST /transfers
  def create
    @transfer = Transfer.new(transfer_params)

    if @transfer.save
      redirect_to @transfer.origin_account, notice: "#{@transfer.origin_account.owner}, Your transfer has been made"
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def transfer_params
      params[:transfer].permit(:money, :origin_account_id, :destiny_account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :owner
    = f.text_field :owner
  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :money
    = f.text_field :money
  = f.hidden_field :bank_id, value: @account.bank.id
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %thead
    %tr
      %th Owner
      %th Number
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.owner
        %td= account.number
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Owner:
  = @account.owner
  %br
  %b Number:
  = @account.number
  %br
  %b Charge:
  = @account.money.format
  %br
  %b Bank:
  = @account.bank.name

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', bank_path(@account.bank)
\|
= link_to 'New transfer', new_account_transfer_path(@account)

- if @transfer_history.empty?
  %p= 'No transactions yet'
- else
  %p
    %h3 Transfers history

  %table{cellpadding: '10'}
    %thead
      %tr
        %th Destiny account
        %th Money
        %th Commission
        %th State
    %tbody
      - @transfer_history.each do |transfer|
        %tr
          %td= transfer.destiny_account.print
          %td
            %b= transfer.money.format
          %td= transfer.commission
          %td= transfer.state

app/views/banks/_form.html.haml
= form_for @bank do |f|
  - if @bank.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bank.errors.count, "error")} prohibited this bank from being saved:"
      %ul
        - @bank.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/banks/edit.html.haml
%h1 Editing bank

= render 'form'

= link_to 'Show', @bank
\|
= link_to 'Back', banks_path

app/views/banks/index.html.haml
%h1 Listing banks

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @banks.each do |bank|
      %tr
        %td= bank.name
        %td= link_to 'Show', bank
        %td= link_to 'Edit', edit_bank_path(bank)
        %td= link_to 'Destroy', bank, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bank', new_bank_path

app/views/banks/new.html.haml
%h1 New bank

= render 'form'

= link_to 'Back', banks_path

app/views/banks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @bank.name

= link_to 'Edit', edit_bank_path(@bank)
\|
= link_to 'Back', banks_path
\|
= link_to 'New account', new_account_path(bank: @bank.id)

- if @accounts.empty?
  %p= 'No accounts yet'
- else
  %p
    %h3 Accounts
  %table
    %thead
      %tr
        %th Owner Name
        %th Number
        %th Charge
        %th
        %th
        %th
    %tbody
      - @accounts.each do |account|
        %tr
          %td= account.owner
          %td= account.number
          %td
            %b= account.money.format
          %td= link_to 'Show', account
          %td= link_to 'Edit', edit_account_path(account)
          %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

- if @transfer_history.empty?
  %p= 'No transactions yet'
- else
  %p
    %h3 Transfers history
  %table{cellpadding: '10'}
    %thead
      %tr
        %th Origin account
        %th Destiny account
        %th Money
        %th Commission
        %th State
    %tbody
      - @transfer_history.each do |transfer|
        %tr
          %td= transfer.origin_account.print
          %td= transfer.destiny_account.print
          %td
            %b= transfer.money.format
          %td= transfer.commission
          %td= transfer.state

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transfers/_form.html.haml
%b=  "from #{@transfer.origin_account.owner}"
= form_for [@origin_account, @transfer] do |f|
  - if @transfer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transfer.errors.count, "error")} prohibited this transfer from being saved:"
      %ul
        - @transfer.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :money
    = f.text_field :money
  = f.hidden_field :origin_account_id, value: @origin_account.id
  .field
    = f.label :destiny_account
    = f.select :destiny_account_id, options_from_collection_for_select(@destiny_accounts, :id, :print)
  .actions
    = f.submit 'Transfer Money'

app/views/transfers/edit.html.haml
%h1 Editing transfer

= render 'form'

= link_to 'Show', @transfer
\|
= link_to 'Back', transfers_path

app/views/transfers/index.html.haml
%h1 Listing transfers

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @transfers.each do |transfer|
      %tr
        %td= link_to 'Show', transfer
        %td= link_to 'Edit', edit_transfer_path(transfer)
        %td= link_to 'Destroy', transfer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Transfer', new_transfer_path

app/views/transfers/new.html.haml
%h1 New transfer

= render 'form'

= link_to 'Back', account_path(@origin_account)

app/views/transfers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_transfer_path(@transfer)
\|
= link_to 'Back', transfers_path